apiVersion: v1
kind: Pod
metadata: 
  name: pod
spec:
  containers:
  - name: app-container
    image: alpine
    command: ["sh", "-c", "sleep 3600"] #Mantem o pod em execução
    volumeMounts: #Define os volumes que serao montados no container
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: app-config #Ref ao configMap criado 
    